### PR TITLE
RKotov. Done 1st homework and 2nd homework

### PR DESCRIPTION
**Pull request by Kotov-Roman**
First homework is ready for checking. Roman Kotov

### CODE REVIEW

**Comment by razyke** [comment]
Please, don't use Intellij code format, use google style (hard to review)

https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

**Comment by Kotov-Roman** [comment]
> Please, don't use Intellij code format, use google style (hard to review)
> 
> https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

**Comment by Kotov-Roman** [comment]
Fixed

**Comment by Kotov-Roman** [comment]
> > Please, don't use Intellij code format, use google style (hard to review)
> > https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

Fixed

**Pull request merged**
